# Generated by Django 3.0.5 on 2020-10-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0002_pat_ap_doc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_profile',
            name='verified',
            field=models.CharField(default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='d_profile',
            name='id_proof',
            field=models.ImageField(upload_to='id'),
        ),
    ]
